/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JamU;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author ufuk
 */
public class Acilis extends javax.swing.JFrame {
     public ImageIcon Fotocek=new ImageIcon(getClass().getResource("/İCONLAR/fotogcekıcn.png"));
      public  ImageIcon Videcek=new ImageIcon(getClass().getResource("/İCONLAR/videocekıcn.png"));
     public  ImageIcon Fotoduz=new ImageIcon(getClass().getResource("/İCONLAR/fotodznıcn.png"));
      public  ImageIcon Videooy=new ImageIcon(getClass().getResource("/İCONLAR/VideoOyntıcn.png"));
       public ImageIcon Fotogos=new ImageIcon(getClass().getResource("/İCONLAR/albmıcn.png"));
       public ImageIcon bos=new ImageIcon(getClass().getResource("/İCONLAR/bos.png"));
       public ImageIcon dol=new ImageIcon(getClass().getResource("/İCONLAR/dol.png"));
    /**
     * Creates new form Acilis
     */
    public Acilis() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JamU");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 204));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İCONLAR/ileri.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İCONLAR/geri.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İCONLAR/fotogcekıcn.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fotoğraf Çek");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İCONLAR/videocekıcn.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jLabel5.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jLabel5.setEnabled(false);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İCONLAR/albmıcn.png"))); // NOI18N
        jLabel6.setEnabled(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İCONLAR/bos.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İCONLAR/bos.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İCONLAR/dol.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İCONLAR/bos.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İCONLAR/bos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(jLabel5)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
     
        jLabel3.setBorder(LineBorder.createBlackLineBorder());
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
       jLabel3.setBorder(null);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
      jLabel4.setBorder(LineBorder.createBlackLineBorder());
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel4.setBorder(null);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        jPanel2.setBorder(LineBorder.createGrayLineBorder());
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        jPanel2.setBorder(null);
    }//GEN-LAST:event_jPanel2MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

        
        
         if ("Fotoğraf Çek".equals(jLabel2.getText())) {
            jLabel2.setText("Video Çek");
            jLabel1.setIcon(Videcek);
            jLabel5.setIcon(Fotoduz);
             jLabel6.setIcon(Fotocek);
             
              jLabel8.setIcon(bos);
            jLabel9.setIcon(dol);
             jLabel10.setIcon(bos);
              jLabel11.setIcon(bos);
            jLabel12.setIcon(bos);
             
        }
        else if("Video Çek".equals(jLabel2.getText())){
        
         jLabel2.setText("Fotoğraf Düzenle");
            jLabel1.setIcon(Fotoduz);
        
          jLabel5.setIcon(Videooy);
             jLabel6.setIcon(Videcek);
             
              jLabel8.setIcon(bos);
            jLabel9.setIcon(bos);
             jLabel10.setIcon(dol);
              jLabel11.setIcon(bos);
            jLabel12.setIcon(bos);
        }
        else if("Fotoğraf Düzenle".equals(jLabel2.getText())){
        
         jLabel2.setText("Video Oynat");
            jLabel1.setIcon(Videooy);
        jLabel5.setIcon(Fotogos);
             jLabel6.setIcon(Fotoduz);
             
              jLabel8.setIcon(bos);
            jLabel9.setIcon(bos);
             jLabel10.setIcon(bos);
              jLabel11.setIcon(dol);
            jLabel12.setIcon(bos);
        
        }
        else if("Video Oynat".equals(jLabel2.getText())){
        
         jLabel2.setText("Fotoğraf Göster");
            jLabel1.setIcon(Fotogos);
            jLabel5.setIcon(Fotocek);
             jLabel6.setIcon(Videooy);
         jLabel8.setIcon(bos);
            jLabel9.setIcon(bos);
             jLabel10.setIcon(bos);
              jLabel11.setIcon(bos);
            jLabel12.setIcon(dol);
        
        }
         else if("Fotoğraf Göster".equals(jLabel2.getText())){
        
         jLabel2.setText("Fotoğraf Çek");
            jLabel1.setIcon(Fotocek);
             jLabel5.setIcon(Videcek);
             jLabel6.setIcon(Fotogos);
              jLabel8.setIcon(dol);
            jLabel9.setIcon(bos);
             jLabel10.setIcon(bos);
              jLabel11.setIcon(bos);
            jLabel12.setIcon(bos);
        }
         
         
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
                if ("Fotoğraf Çek".equals(jLabel2.getText())) {
            jLabel2.setText("Fotoğraf Göster");
            jLabel1.setIcon(Fotogos);
             jLabel5.setIcon(Fotocek);
             jLabel6.setIcon(Videooy);
             
              jLabel8.setIcon(bos);
            jLabel9.setIcon(bos);
             jLabel10.setIcon(bos);
              jLabel11.setIcon(bos);
            jLabel12.setIcon(dol);
             
             
        }
        else if("Video Çek".equals(jLabel2.getText())){
        
         jLabel2.setText("Fotoğraf Çek");
            jLabel1.setIcon(Fotocek);
         jLabel5.setIcon(Videcek);
             jLabel6.setIcon(Fotogos);
                     jLabel8.setIcon(dol);
            jLabel9.setIcon(bos);
             jLabel10.setIcon(bos);
              jLabel11.setIcon(bos);
            jLabel12.setIcon(bos);
        
        }
        else if("Fotoğraf Düzenle".equals(jLabel2.getText())){
        
         jLabel2.setText("Video Çek");
            jLabel1.setIcon(Videcek);
         jLabel5.setIcon(Fotoduz);
             jLabel6.setIcon(Fotocek);
             
             jLabel8.setIcon(bos);
            jLabel9.setIcon(dol);
             jLabel10.setIcon(bos);
              jLabel11.setIcon(bos);
            jLabel12.setIcon(bos);
        
        }
        else if("Video Oynat".equals(jLabel2.getText())){
        
         jLabel2.setText("Fotoğraf Düzenle");
            jLabel1.setIcon(Fotoduz);
            jLabel5.setIcon(Videooy);
             jLabel6.setIcon(Videcek);
             
             
             jLabel8.setIcon(bos);
            jLabel9.setIcon(bos);
             jLabel10.setIcon(dol);
              jLabel11.setIcon(bos);
            jLabel12.setIcon(bos);
        
        }
         else if("Fotoğraf Göster".equals(jLabel2.getText())){
        
         jLabel2.setText("Video Oynat");
            jLabel1.setIcon(Videooy); 
            jLabel5.setIcon(Fotogos);
             jLabel6.setIcon(Fotoduz);
     
        
             jLabel8.setIcon(bos);
            jLabel9.setIcon(bos);
             jLabel10.setIcon(bos);
              jLabel11.setIcon(dol);
            jLabel12.setIcon(bos);
             
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        if ("Fotoğraf Çek".equals(jLabel2.getText())) {
            Fotografcek c1=new Fotografcek();
            c1.setVisible(true);
           dispose();
        }
        else if("Video Çek".equals(jLabel2.getText())){
        
         
        VideoCek c2=new VideoCek();
        c2.setVisible(true);
        dispose();
        
        }
        else if("Fotoğraf Düzenle".equals(jLabel2.getText())){
        
         FotografDuzenle c3=new FotografDuzenle();
        c3.setVisible(true);
         dispose();
        
        }
        else if("Video Oynat".equals(jLabel2.getText())){
        
         VideoOynat c4=new VideoOynat();
         c4.setVisible(true);
         dispose();
        
        }
         else if("Fotoğraf Göster".equals(jLabel2.getText())){
        
         FotografGoster c5=new FotografGoster();
        c5.setVisible(true);
        dispose();
        }
        
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         if ("Fotoğraf Çek".equals(jLabel2.getText())) {
            Fotografcek c1=new Fotografcek();
            c1.setVisible(true);
           dispose();
        }
        else if("Video Çek".equals(jLabel2.getText())){
        
         
        VideoCek c2=new VideoCek();
        c2.setVisible(true);
        dispose();
        
        }
        else if("Fotoğraf Düzenle".equals(jLabel2.getText())){
        
         FotografDuzenle c3=new FotografDuzenle();
        c3.setVisible(true);
         dispose();
        
        }
        else if("Video Oynat".equals(jLabel2.getText())){
        
         VideoOynat c4=new VideoOynat();
         c4.setVisible(true);
         dispose();
        
        }
         else if("Fotoğraf Göster".equals(jLabel2.getText())){
        
         FotografGoster c5=new FotografGoster();
        c5.setVisible(true);
        dispose();
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         if ("Fotoğraf Çek".equals(jLabel2.getText())) {
            Fotografcek c1=new Fotografcek();
            c1.setVisible(true);
           dispose();
        }
        else if("Video Çek".equals(jLabel2.getText())){
        
         
        VideoCek c2=new VideoCek();
        c2.setVisible(true);
        dispose();
        
        }
        else if("Fotoğraf Düzenle".equals(jLabel2.getText())){
        
         FotografDuzenle c3=new FotografDuzenle();
        c3.setVisible(true);
         dispose();
        
        }
        else if("Video Oynat".equals(jLabel2.getText())){
        
         VideoOynat c4=new VideoOynat();
         c4.setVisible(true);
         dispose();
        
        }
         else if("Fotoğraf Göster".equals(jLabel2.getText())){
        
         FotografGoster c5=new FotografGoster();
        c5.setVisible(true);
        dispose();
        }
        
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jPanel2.setBorder(LineBorder.createGrayLineBorder());
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jPanel2.setBorder(null);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
         jPanel2.setBorder(LineBorder.createGrayLineBorder());
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
         jPanel2.setBorder(null);
    }//GEN-LAST:event_jLabel2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acilis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acilis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acilis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acilis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Acilis().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
